spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usercenter?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver

# Server settings (ServerProperties)
---
spring:
    profiles: dev
server:
  port: 8080
---
spring:
      profiles: qa
server:
    port: 8081
---
spring:
      profiles: prod
server:
    port: 8082

# Tomcat specifics
tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs